"""Added initial table

Revision ID: ff874d878b9c
Revises: 
Create Date: 2023-12-03 02:10:47.828529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff874d878b9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score'))
    )
    op.create_index(op.f('ix_score_id'), 'score', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_id'), table_name='score')
    op.drop_table('score')
    # ### end Alembic commands ###
